# Generated by Django 2.2.2 on 2019-07-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=20)),
                ('Manufacturer', models.CharField(max_length=20)),
                ('Package_Dimensions', models.IntegerField()),
                ('ASIN', models.CharField(max_length=30)),
                ('Best_Seller_Rank', models.IntegerField()),
                ('Band_color', models.CharField(max_length=20)),
                ('Band_material', models.CharField(max_length=20)),
                ('Brand', models.CharField(max_length=20)),
                ('Collection', models.CharField(max_length=20)),
                ('Dial_color', models.CharField(max_length=20)),
                ('Crystal', models.CharField(max_length=20)),
                ('Display_type', models.CharField(max_length=20)),
                ('Case_Shape', models.CharField(max_length=20)),
                ('Model_Number', models.CharField(max_length=20)),
                ('Part_Number', models.CharField(max_length=20)),
                ('Special_Features', models.CharField(max_length=20)),
                ('Warranty_Type', models.CharField(max_length=20)),
                ('Movement', models.CharField(max_length=20)),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(default=None, upload_to='images')),
                ('img3', models.ImageField(default=None, upload_to='images')),
                ('img4', models.ImageField(default=None, upload_to='images')),
            ],
        ),
    ]
