# Generated by Django 2.2.2 on 2019-07-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staunishing', '0003_cart_category_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img5',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='img6',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='img7',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
