# Generated by Django 2.2.2 on 2019-07-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staunishing', '0005_auto_20190712_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Name',
            field=models.CharField(default='Sample', max_length=50),
        ),
    ]
