# Generated by Django 2.2.2 on 2019-07-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staunishing', '0006_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Cat',
            field=models.ForeignKey(default=None, on_delete='CASECADE', to='staunishing.Category'),
        ),
    ]
