# Generated by Django 2.2.2 on 2019-07-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staunishing', '0007_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Cat',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='staunishing.Category'),
        ),
    ]
