# Generated by Django 2.2.2 on 2019-07-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staunishing', '0008_auto_20190712_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Cat',
        ),
    ]
