# Generated by Django 2.2.2 on 2019-07-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staunishing', '0009_remove_product_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='staunishing.Category'),
        ),
    ]
