# Generated by Django 2.2.2 on 2019-07-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staunishing', '0010_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
