# Generated by Django 2.2.2 on 2019-07-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staunishing', '0011_auto_20190713_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=200),
        ),
    ]
