# Generated by Django 2.2.2 on 2019-07-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staunishing', '0012_auto_20190713_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=500),
        ),
    ]
